### ISSUE TITLE
Turn off variable shadowing warning

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#143]
I've always felt this warning was actively harmful. Looking at the code, I can see places where you have actively harmed your code to adhere to it :(

    digest list = case list of
        []  -> "none"
        [x] -> x
        xs  -> head xs ++ " (and " ++ show (length xs - 1) ++ " more)"

In any normal code I would expect `digest xs`, but then you get name shadowing - a harmless situation, but which leads to a warning.

I appreciate this is personal preference, but I always turn off this warning.

**Comment by snowleopard** [comment]
To be honest I never found it difficult to fix this warning if need be. I do agree that in most cases it doesn't actually highlight an error, although on rare occasions I found it useful.

In the above example, I find that `digest list` actually reads better, but only marginally, so I don't mind to accept the change you proposed in #144.

> I've always felt this warning was actively harmful.

Can you elaborate? I may underestimate the harm. My current understanding is that it only forces us to hide unused imports, which is indeed annoying.

**Comment by ndmitchell** [comment]
I often use variable shadowing to reduce the possibility of error. For example, in digest, if you use xs as the scrutinee and the test then you can guarantee in the alternative that you don't refer to the wrong variable, since it's shadowed. It's even more useful in large monadic blocks to avoid things you have "updated".

I generally find it to be annoying and make my code less robust, so always turn it off. But it's ultimately up to your preferences and I'll follow.

**Comment by angerman** [comment]
The two sides of this coin we are discussing are the following, if I understand correctly:

- One the one side (and I think this is the intended warning for the warning), you want to prevent using variables you think refer to something in a more global scope but you accidentally shadowed it by a local binding you might not have noticed to have done so actually. In this case it prevents a case of hard to debug errors, but also requires that both bindings are of the same type!
- On the other side, we have the issue of explicitly finding new names for local variables that would be more concise using a common naming scheme. Or the inverse case of the first side, which @ndmitchell alludes to, in that you *want* the local binding, but accidentally obtain the global binding because you forgot to rename your variable in your subscope.

If you stick to the idea of having a consistent naming scheme, you should not run afoul of the second point, as a binding will always refer to the most recent one. But then the shadowing warning makes no sense, as shadowing is part of your style.

I don't see a clear stronger side here. Both do not prevent you from using the wrong name. The first one though keeps *all* bindings in scope, while the second one can purposefully reduce the number of bindings in scope by actively using shadowing.

I feel I'm a bit more on @ndmitchell's side, as less bindings should mean less potential to use the wrong binding.

From a language point of view I guess shadowing can be considered messy. From a users point of view, too many bindings might be considered messy.

**Comment by snowleopard** [comment]
OK, let's switch the warning off. I never used shadowing purposefully, but this may indeed be useful. My Haskell coding style is not yet settled and my preferences are vague (I'm a newbie), so I can switch from one to another and see how it goes. 

@ndmitchell Could you do this as part of you PR?
