### ISSUE TITLE
Test and fix the profiling way

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#186]
We currently disable the `profiling` way in `Settings/User.hs`, partly to speed up default builds. However, it may actually work correctly. We need to test it and consider enabling it by default.
- [x] Test and fix the `profiling` way
- [x] Consider enabling it by default or as part of the `profiling` flavour
- [x] Add a command line flag to enable/disable `profiling`

**Comment by thomie** [comment]
Just a heads up: `mk/flavours/prof.mk` is for profiling GHC itself (and hardly anyone ever does, that's why it so slow, ha ha ha). To profile GHC, you need to build the libraries the `p` way first. Some build flavours skip this by setting `BUILD_PROF_LIBS=NO`.

GHC releases don't ship with a profiled GHC. They do include a copy of the libraries built the `p` way (excluding the `ghc` library), so users can profile *their* code.

**Comment by snowleopard** [comment]
@thomie Good to know, thanks! I didn't realise libraries and GHC were treated differently w.r.t `profiling`.

**Comment by snowleopard** [comment]
Library profiling seems to work in my tests, so I am closing this issue.

Building a profiled GHC (`GhcProfiled = YES`) is another matter, which I think deserves a separate issue.
