### ISSUE TITLE
Add clang support

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#26]
build.sh for some reason fails to find clang.
```
Linking shake-build/.shake/build ...
Reading shake-build/cfg/system.config...
Reading package dependencies...
| Successfully generated 'utils/hp2ps/stage0/package-data.mk'.
Reading utils/hp2ps/stage0/package-data.mk...
Reading dependencies from utils/hp2ps/stage0/build/.dependencies...
Error when running Shake build system:
* inplace/bin/hp2ps
* utils/hp2ps/stage0/build/Utilities.o
* OracleQ (DependenciesKey ("utils/hp2ps/stage0/build/.dependencies","utils/hp2ps/stage0/build/Utilities.o"))
* utils/hp2ps/stage0/build/.dependencies
* utils/hp2ps/stage0/build/Utilities.c.deps
* clang
Error, file does not exist and no rule available:
  clang
```

**Comment by snowleopard** [comment]
Right. So far I only worked with `gcc` compiler. Perhaps, it is worth raising a separate issue for adding `clang` support?

As a temporary workaround, can you force the build system to use `gcc` instead of `clang`?

**Comment by angerman** [comment]
Ohh. So we won't be able to build with llvm anyway? Good to know. Do you have any initial pointers for where to start implementing `clang` support?

**Comment by snowleopard** [comment]
It may be not too difficult to add a proper support for `clang`, so feel free to give it a try. It is a nice task which should not interact badly with other parts of the build system.

If you create a new issue for this we can try to go through all the necessary fixes together. For example, the first one is that the build system doesn't know where `clang` lives to verify that it exists and it doesn't have to be built first. You can either provide the full path somehow (perhaps, via some `configure` trickery?) or temporarily disable `need clang` which happens when `clang` is called.

**Comment by angerman** [comment]
A temporary work around is explicitly setting the `gcc` path with
```
./configure --with-gcc=$(which clang)
```
On Mac `WhatGccIsCalled` end's up being `clang`, with no path.

**Comment by snowleopard** [comment]
Looks good! This could eventually be added to `configure.ac`, the section responsible for the new build system.

Any other `clang`-specific issues?

**Comment by angerman** [comment]
So far, nothing other than what is already reported as bug. I'll try to put that in a PR with a note tomorrow.

**Comment by snowleopard** [comment]
I have a feeling we will have more issues with `clang`, because `clang` and `gcc` might want different flags.

We should probably rename `Gcc` builder to `CCompiler` and then have a way to determine which compiler we use in order to generate appropriate flags in `Settings/Builder/Gcc.hs` (also to be renamed to `Settings/Builder/CCompiler.hs`).

**Comment by angerman** [comment]
I'm certain we will. Yet `clang` tries hard to be a substitute for `gcc`.
On OS X, `/usr/bin/gcc` is the following:
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```
