### ISSUE TITLE
Parallel compilation appears to be broken

### ISSUE THREAD

**Issue by bgamari** [snowleopard/shaking-up-ghc#3]
Running with `-jN` where N > 1 results in failures of the form,
```
No dependencies found for 'libraries/process/dist-install/build/libHSprocess-1.4.1.0.ghc7.11.20151216.so'.
```
on Linux.

**Comment by bgamari** [comment]
I suppose the issue is likely to do with the rules in `Rules.Dependencies` missing dependencies.

**Comment by snowleopard** [comment]
Two issues seem to be mixed here:
1) I confirm that parallel build is currently broken. The reason is that I fail to track dependencies due to `-package-id` flags passed to GHC.
2) Dynamic libraries are not built at the moment: there are no rules at all for "*.so" files. I need to disable dynamic way on Linux to silent related errors (setting `userLibWays = remove [dynamic]` in `Settings/User.hs` should do the trick for you).

`Rules.Dependencies` is most probably innocent.

**Comment by bgamari** [comment]
> I confirm that parallel build is currently broken. The reason is that I fail to track dependencies due to `-package-id` flags passed to GHC.
How do you envision these will be tracked? Parsing the package name out of the package ids and then looking up its targets?

**Comment by snowleopard** [comment]
@bgamari That's correct. I've just fixed this issue. Will push the updates after a test build.

**Comment by bgamari** [comment]
Brilliant! Looking forward to seeing the result.

**Comment by snowleopard** [comment]
Done:
* This fixes missing dependencies: 361c3c2.
* This temporarily drops `profiling` and `dynamic` ways: f4fb52d.

Note, parallel build still sometimes fails on Windows due to a segfault in ghc (also mentioned here: https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation/Windows), in which case a restart helps.

**Comment by snowleopard** [comment]
@bgamari I've opened a new issue regarding `dynamic` way: #4. Feel free to pick this up if you'd like to keep hacking on the new build system. This may be easier for you to fix, because I think you have a better understanding of how `dynamic` way works. Thank you!

**Comment by bgamari** [comment]
Thanks @snowleopard! Indeed I think I'll take a stab at #4.

**Comment by snowleopard** [comment]
@bgamari Awesome! Thanks again.
