### ISSUE TITLE
How to correctly reset?

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#32]
What are the expected commands to run to end up with a completely clean state, to start from? Or should one reclone the repositories every time?

Running the following, seems like a pretty excessive way to arrive at the initial state.
```
$ git clone git://git.haskell.org/ghc
$ cd ghc
$ git submodule update --init
$ git clone git://github.com/snowleopard/shaking-up-ghc shake-build
```

**Comment by quchen** [comment]
This is indeed missing a `clean` target. @snowleopard Why do we modify the GHC source tree at all, instead of building everything in a _build directory? I think it would be a great benefit to be able to `clean` the GHC source tree by simply deleting a single directory. No clutter, no accidentially left-over files, and it would be clear where to look for things if you need some `.o` file.

**Comment by angerman** [comment]
@quchen :+1: for using `_build`

**Comment by snowleopard** [comment]
We are currently modifying the GHC tree, because we partially depend on the results produced by the old build system. It was much easier for me to start working on the project and experiment with the overall design by taking care of some easy parts, instead of doing things completely from scratch.

I agree that putting everything in a single directory would be great. I would propose to use `.build` instead of `_build` though to match existing naming conventions (`.git`, `.arc-linters`, etc).

However, I'm not sure we are ready to become fully independent of the old build system. If we do that then we reduce our ability to work in parallel: at the moment contributors can independently work on different parts of the build system, filling in blank spots, while the overall build succeeds (at least it succeeds for me on Windows producing GHC executables). We will lose this if we switch to the working-from-scratch mode.

Can I ask why you'd like the ability to come to the initial state? When I'd like *to reset the new build system* I simply delete the `shake-build/.db` directory and let Shake run all currently implemented build rules. For Shake it doesn't really matter whether old files are still there or they have been deleted: it will make sure to rebuild them anyway when the Shake database is missing.

**Comment by bgamari** [comment]
I agree that moving build artifacts in `.build` is ultimately the right thing to do.

However, I also agree that we have a ways to go before we can completely break free of the `make` build system. Let's keep this on the back burner until we can reliably do full builds.

**Comment by angerman** [comment]
My reasoning for being able to reset everything to the initial state is my distrust of build (esp. make) systems. Usually one expects a build system to properly rebuild everything that needs to be on changes in the source tree, if this does not properly work, one has to resort to rebuild everything, hence a way to get back to a clean state (removing all build products) to start over building again (preferably without losing ones changes). This, to my understanding, applies even more if one is hacking on the build system itself.

As @snowleopard pointed out shakes dependence on the build database, is probably a good temporary solution.

Can we somehow turn this into a command, or should I add that to the README?

**Comment by quchen** [comment]
@angerman, if you haven't heard of `lndir` yet: there's a really nice script in the `util`s that allows you to recursively link an entire directory tree. You `lndir ghc`, and build inside the clone; when you delete the clone, you've got a completely untouched GHC again. And the nice thing is that if you edit the clone tree, you edit the links, hence the original sources - so you can work on GHC just the same way, but you get a free super-clean.

`lndir` is of course a hack because the `make` build system spams its output all over the place; if we used a `.build` directory via GHC-Shake, we'd get the same effect more portable and natively by the build system.

**Comment by angerman** [comment]
@quchen indeed, I have not! Thanks for pointing out `lndir`.

Should we then include `lndir` and 
```
make maintainer-clean && git clean -df && ./boot && ./configure
```
as steps to reset to the README?

If we agree on this being useful (I would), I would go ahead and draft a README.md PR to discuss this further.

**Comment by quchen** [comment]
`lndir` is an optional part of using the build system, but mentioning it would probably be useful. (I wonder how many other things in utils/ that I've never heard of are useful as well.)

**Comment by snowleopard** [comment]
I think it is good to add a short section on how to reset the build. Something like this?

Resetting the build
-------------------------
To reset the new build system delete the `shake-build/.db` directory which stores the Shake database. This will force Shake to rerun all rules, even if the results of the previous build are still in the GHC tree. This is a temporary solution; we are working on a proper reset functionality (see #32).

**Comment by angerman** [comment]
@snowleopard sounds good to me :+1:

I need to get a little more acquainted with `lndir`, and would add a second paragraph regarding `lndir` and resetting the artifacts in the build tree as well. As long as we are running `make` and `shake` in parallel, that would probably be useful as well.

**Comment by snowleopard** [comment]
Done: https://github.com/snowleopard/shaking-up-ghc/blob/master/README.md#resetting-the-build

@angerman Yes, please add a paragraph about `lndir` too.

**Comment by quchen** [comment]
Doesn't the `-B` flag trigger a full rebuild as well? No need to lose the entire Shake database (which contains timing information, for example)

**Comment by snowleopard** [comment]
Hmm, indeed, `-B` seems to work! I never came across it for some reason.

Thanks @quchen, I'll update `README`.

**Comment by angerman** [comment]
I've just played with `lndir`. Like so:
```
$ mkdir ghc+ && lndir $(pwd)/ghc $(pwd)/ghc+ 
```
This however brought up an issue when trying to locale `inplace/lib/template-hsc.h`, which shake expected in `ghc`, even though `shake` was run from `ghc+`.
