### ISSUE TITLE
Prerequisites and cabal sandbox

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#37]
The addition of the cabal sandbox section has dropped the prerequisite sections, was this on purpose or an oversight?

@quchen should the cabal sandbox build, install `alex` and `shake` as well?

**Comment by quchen** [comment]
The .cabal lists Shake as a dependency. I didn't even know it also came with an executable! I'm not sure what the latter would be useful for in terms of this project.

I've removed the section because I thought it was unhelpful in its current form, not because I think it's not useful in general. [See my comment here.](https://github.com/snowleopard/shaking-up-ghc/pull/28#issuecomment-167063357)

I think the ideal solution would be having a script that checks all the prerequisites before running the build system, detailing what's missing in order to

1. build GHC in general; this would include errors if `Alex` or `Happy` or `GHC` are not installed
2. build GHC-Shake; this part may be unnecessary, since we can auto-install everything in a sandbox (which is what the `build.cabal.sh` script currently does).

**Comment by angerman** [comment]
I see. I completely missed that comment. I would still like to have
an exhaustive list of prerequisites, until we have a script that checks
for them. What would you consider essential?

**Comment by angerman** [comment]
So given a completely blank starting point, what would one need to initiate the first build?

**Comment by quchen** [comment]
@angerman The GHC building guide talks about this: https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation

**Comment by snowleopard** [comment]
So, the exhaustive list of prerequisites is something like this: *Everything listed in `shaking-up-ghc.cabal` and whatever else the GHC building guide mentions*. Is that correct?

**Comment by angerman** [comment]
That sounds like it should get someone completely new to the project get started. :+1:
